---
title: "Título"
author: "Igo da Costa Andrade"

# Metadados
booktitle: "Understanding Physics for JEE"
booksubtitle: "Mechanics 1"
bookauthors: "Pandney, S."
bookaddres: "New Delhi"
bookpublisher: "Arihant Publications"
bookyear: "2000"
chaptertitle: "Measurement and Errors"
chapternumber: "2"
maincolor: "d41d24"

output: 
  bookdown::pdf_document2:
    template: template.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reticulate)
use_python("~/.envs/science/bin/python")
```


\section*{Questões Objetivas}

\begin{enumerate}
  \item O número de algarismos significativos em 3400 é:
  \begin{enumerate}
    \item 3
    \item 1
    \item 4
    \item 2
  \end{enumerate}
  \iniSol
    Observemos que $3400 = 3,4 \times 10^3$. Assim, temos dois algarismos significativos, a saber, 3 e 4. Portanto, a resposta correta é o item D.
  \fimSol
  %%%%
  \item Os algarismos significativos no número $6,0023$ são:
  \begin{enumerate}
    \item 2
    \item 5
    \item 4
    \item 3
  \end{enumerate}
  \iniSol
    Temos cinco algarismos significativos em $6,0023$: $6, 0, 0, 2, \text{ e } 3$. Resposta correta: item B.
  \fimSol
  %%%%
  \item O comprimento e a largura de uma folha de metal são $3,124$ m e $3,002$ m, respectivamente. A área desta folha, arredondada para o número correto de algarismos significativos, é:
  \begin{enumerate}
    \item $9,378\text{ m}^2$
    \item $9,37\text{ m}^2$
    \item $9,4\text{ m}^2$
    \item Nenhuma das anteriores.
  \end{enumerate}
  \iniSol
    $$
      \text{Área} = \text{Comprimento} \times \text{Largura} = 3,124 \times 3,002 =  9,378248
    $$
    Com a correta quantidade de algarismos significativos, $\text{Área} = 9,378\text{ m}^2$. Resposta: item A.
  \fimSol
  %%%%
  \item O comprimento, a largura e a espessura de um bloco são dadas por $l = 12$ cm, $b = 6$ cm e $t = 2,45$ cm. O volume do bloco, de acordo com o conceito de algarismos significativos, deve ser:
  \begin{enumerate}
    \item $1 \times 10^2\text{ cm}^3$
    \item $2 \times 10^2\text{ cm}^3$
    \item $1,763 \times 10^2\text{ cm}^3$
    \item 1Nenhuma das anteriores.
  \end{enumerate}
  \iniSol
    $$
    V = l \times b \times t = 12 \times 6 \times 2,45 = 176,4 \text{ cm}^3 = 1,764 \times 10^2 \text{ cm}^3
    $$
    Note-se que o comprimento ($l$), a largura ($b$) e a espessura ($t$) possuem respectivamente 2, 1 e 3 algarismos significativos. A resposta do volume $V = l \times b \times t$ deve ser arredondada para a menor quantidade de algarismos significativos das quantidades dadas, ou seja, 1 (um) algarismos significativo. Portanto, de acordo com o conceito de algarismos significativos:
    $$ V = 2 \times 10^2 \text{ cm}^3 $$
    Reposta correta: item B.
  \fimSol
  %%%%
  \item Se o erro na medição do raio de uma esfera é de 1\%, qual será o erro na medição do volume?
  \begin{enumerate}
    \item 1\%
    \item $\dfrac{1}{3}$\%
    \item 3\%
    \item 1Nenhuma das anteriores.
  \end{enumerate}
  \iniSol
  Consideremos a fórmula para o volume $V$ de uma esfera de raio $R$: $$V = \dfrac{4}{3}\pi R^3$$
  Tomando diferenciais em ambos os lados da equação, temos:
  \begin{align*}
    V = \dfrac{4}{3} \pi R^3 &\Rightarrow dV = \dfrac{4}{3}\pi \left(3R^2 dR\right) \Rightarrow dV = \dfrac{4}{3}\pi R^3 \left(3\dfrac{dR}{R}\right) \Rightarrow \dfrac{dV}{V} = 3 \dfrac{dR}{R} \Rightarrow \dfrac{\Delta V}{V} = 3 \dfrac{\Delta R}{R}
  \end{align*}
  Dado que $\dfrac{\Delta R}{R} = 1\%$, temos:
  $$
  \dfrac{\Delta V}{V} = 3 \dfrac{\Delta R}{R} = 3 \cdot 1\% = 3\%
  $$
  Resposta correta: item C.
  \fimSol
  %%%%
  \item A densidade de um cubo é determinada medindo sua massa e o comprimento de seus lados. Se o erro máximo na medição da massa e do comprimento for de 4\% e 3\%, respectivamente, o erro máximo na medição da densidade será:
  \begin{enumerate}
    \item 7\%
    \item 9\%
    \item 12\%
    \item 13\%
  \end{enumerate}
  \iniSol
    Seja o volume ($V$) do cubo dado por $V = l^3$, em que $l$ é comprimento de seus lados. Assim,
    \begin{align*}
      \rho = \dfrac{m}{V} \Rightarrow \rho = \dfrac{m}{l^3}  &\Rightarrow d \rho = \dfrac{dm \cdot l^3 - m \cdot (3l^2 dl)}{(l^3)^6} \Rightarrow \dfrac{d \rho}{\rho} = \dfrac{\dfrac{dm \cdot l^3 - m \cdot (3l^2 dl)}{(l^3)^6}}{\dfrac{m}{l^3}}\\
      &\Rightarrow \dfrac{d \rho}{\rho} = \dfrac{dm}{m} - 3\dfrac{dl}{l}\\
      &\Rightarrow \left(\dfrac{\Delta \rho}{\rho}\right)_{max} = max \left(\pm \dfrac{\Delta m}{m} \mp 3 \dfrac{\Delta l}{l}\right)\\
      &\Rightarrow \left(\dfrac{\Delta \rho}{\rho}\right)_{max} = \dfrac{\Delta m}{m} + 3\dfrac{\Delta l}{l} = 4\% + 3 \cdot 3\%= 13\%
    \end{align*}
    Resposta Correta: item D.
  \fimSol
  %%%%
  \item O erro percentual na medição da massa e da velocidade é de 2\% e 3\%, respectivamente. O erro na medição da energia cinética, obtido a partir da medição da massa e da velocidade, será:
  \begin{enumerate}
    \item 12\%
    \item 10\%
    \item 8\%
    \item 5\%
  \end{enumerate}
  \iniSol
  \begin{align*}
    K = \dfrac{1}{2}mv^2 &\Rightarrow dK = \dfrac{1}{2} dm v^2 + \dfrac{1}{2} m (2v dv) \Rightarrow \dfrac{d K}{K} = \dfrac{\dfrac{1}{2} dm v^2 + \dfrac{1}{2} m (2v dv)}{\dfrac{1}{2}m v^2}\\
    &\Rightarrow \dfrac{dK}{K} = \dfrac{dm}{m} + 2 \dfrac{dv}{v}\\
    &\Rightarrow \left(\dfrac{\Delta K}{K}\right)_{max} = max \left(\pm \dfrac{\Delta m}{m} \pm 2 \dfrac{\Delta v}{v}\right)\\
    &\Rightarrow \left(\dfrac{\Delta K}{K}\right)_{max} = \dfrac{\Delta m}{m} + \dfrac{\Delta v}{v} = 2\% + 2 \cdot 3\% = 8\%
  \end{align*}
  Resposta correta: item C.
  \fimSol
  %%%%
  \item Uma força \( F \) é aplicada em uma placa quadrada de lado \( L \). Se o erro percentual na determinação de \( L \) é de 2\% e o de \( F \) é de 4\%, qual é o erro permitido na pressão?
  \begin{enumerate}
    \item 8\% 
    \item 6\%
    \item 4\%
    \item 2\%
  \end{enumerate}
  \iniSol
    \begin{align*}
      p = \dfrac{F}{A} \Rightarrow p = \dfrac{F}{L^2} & \Rightarrow dp = \dfrac{dF L ^2 - F (2L dL)}{L^2} \Rightarrow \dfrac{dp}{p} = \dfrac{\dfrac{dF L ^2 - F (2L dL)}{L^2}}{\dfrac{F}{L^2}}\\
      &\Rightarrow \dfrac{dp}{p} = \dfrac{dF}{F} - 2\dfrac{dL}{L}\\
      &\Rightarrow \left(\dfrac{\Delta p}{p}\right)_{max} =  max \left(\pm \dfrac{\Delta F}{F} \mp 2 \dfrac{\Delta L}{L}\right)\\
       &\Rightarrow \left(\dfrac{\Delta p}{p}\right)_{max} = \dfrac{\Delta F}{F} + 2 \dfrac{\Delta L}{L} = 4\% + 2 \cdot 2\% = 8\%
    \end{align*}
    Resposta Correta: item A.
  \fimSol
  %%%%
  \item O calor gerado em um circuito depende da resistência, da corrente e do tempo durante o qual a corrente flui. Se o erro na medição desses valores é de 1\%, 2\% e 1\%, respectivamente, então o erro máximo na medição do calor é:
  \begin{enumerate}
    \item 8\%
    \item 6\%
    \item 18\%
    \item 12\%
  \end{enumerate}
  \iniSol
    A potência dissipada em um circuito com resistência $R$, no qual circula uma correten $i$ é dada por $P = Ri^2$. Assim, o calor $H$ gerado num tempo $t$ é:
    $$H = Ri^2 t$$
    Portanto, diferenciando a equação acima, obtemos
    \begin{align*}
      dH = d(Ri^2) t + Ri^2 dt = dR i^2 t + R (2i di) t + Ri^2 dt & \Rightarrow \dfrac{dH}{H} = \dfrac{dR i^2 t + R (2i di) t + Ri^2 dt}{Ri^2 t} \\
      &\Rightarrow \dfrac{dH}{H} = \dfrac{dR}{R} + 2\dfrac{di}{i} + \dfrac{dt}{t}\\
      &\Rightarrow \left(\dfrac{\Delta H}{H}\right)_{max} = max\left(\pm \dfrac{\Delta R}{R} \pm 2 \dfrac{\Delta i}{i} \pm \dfrac{\Delta t}{t}\right)\\
      &\Rightarrow \left(\dfrac{\Delta H}{H}\right)_{max} = \dfrac{\Delta R}{R} +2\dfrac{\Delta i}{i} + \dfrac{\Delta t}{t}\\
      &\Rightarrow \left(\dfrac{\Delta H}{H}\right)_{max} = 1\% + 2 \cdot 2\% + 1\% = 6\%
    \end{align*}
    Resposta Correta: item B.
  \fimSol
  %%%%
  \item Seja \( g \) a aceleração devido à gravidade na superfície da Terra e \( K \) a energia cinética rotacional da Terra. Suponha que o raio da Terra diminua em 2\%. Mantendo todas as outras quantidades constantes, então:
  \begin{enumerate}
    \item $g$ aumenta 2\% e $K$ aumenta 2\%.
    \item $g$ aumenta 4\% e $K$ decresce 4\%.
    \item $g$ decresce 4\% e $K$ decresce 2\%.
    \item $g$ decresce 2\% e $K$ decresce 4\%.
  \end{enumerate}
  \iniSol
  Seja $R$ o raio da Terra. A aceleração da gravidade $g$ na superfície terrestre é dada por:
  $$
    g = \dfrac{G M}{R^2}
  $$
  em que $G = 6,67 \times 10^{-11} \text{ m}^3\text{kg}^{-1}\text{s}^{-2}$ é a constante de gravitação universal e $M$ é a massa da Terra. Considerando uma redução percentual $\dfrac{\Delta R}{R} = 2\%$ no raio terrestre e mantendo as demais quantidades constantes, temos:
  \begin{align*}
    g = GM R^{-2} &\Rightarrow dg = GM (-2R^{-3} dR) \Rightarrow \dfrac{dg}{g} = \dfrac{-2GMR^{-3}dR}{GMR^{-2}}\\
    &\Rightarrow \dfrac{dg}{g} = - 2\dfrac{dR}{R} \Rightarrow \dfrac{\Delta g}{g} = - 2\dfrac{\Delta R}{R} = - 2 \cdot (-2\%) = +4\%
  \end{align*}
  A energia cinética de rotação da Terra é $$K = \dfrac{1}{2}I\omega^2$$
  em que $I = \dfrac{2}{5}MR^2$ é o momento de inércia da Terra, considerada esférica e $\omega$ é a velocidade angular de rotação. Assim:
  $$
  K = \dfrac{1}{5}MR^2\omega^2
  $$
  Diferenciando a equação acima e considerando apenas a variação do raio $R$, temos:
  \begin{align*}
  dK = \dfrac{1}{5}M\omega^2 (2RdR) & \Rightarrow \dfrac{dK}{K} = \dfrac{\dfrac{1}{5}M\omega^2 (2RdR)}{\dfrac{1}{5}MR^2\omega^2}\\
  &\Rightarrow \dfrac{dK}{K} = 2\dfrac{dR}{R}\\
  &\Rightarrow \dfrac{\Delta K}{K} = 2 \dfrac{\Delta R}{R} = 2 \cdot (-2\%) = -4\%
  \end{align*}
  Portanto, uma diminuição de 2\% no raio da Terra provoca um aumento de 4\% na aceleração da gravidade $g$ e uma diminuição de 4\% na energia cinética de rotação.
  
  \fimSol
  %%%%
  \item Uma quantidade física $A$ é dependente de outras quatro quantidades físicas $p$, $q$, $r$ e $s$ por meio da equaçãção $A = \dfrac{\sqrt{pq}}{r^2s^3}$. O erro percentual das medidas de $p$, $q$, $r$ e $s$ são 1\%, 3\%, 0,5\% e 0.33\%, respectivamente, então o erro percentual máximo de $A$ é:
  \begin{enumerate}
    \item 2\%
    \item 0\%
    \item 4\%
    \item 3\%
  \end{enumerate}
  \iniSol
  \begin{small}
  \begin{align*}
    A = \dfrac{\sqrt{pq}}{r^2s^3} & \Rightarrow A = p^{1/2}q^{1/2} r^{-2}s^{-3} \Rightarrow dA = d(p^{1/2}) q^{1/2} r^{-2}s^{-3} + p^{1/2}d(q^{1/2} r^{-2}s^{-3})\\
    &\Rightarrow dA = \left(\dfrac{1}{2}p^{-1/2}dp\right)q^{1/2} r^{-2}s^{-3} + p^{1/2} \left[d(q^{1/2})r^{-2}s^{-3} + q^{1/2}d(r^{-2}s^{-3})\right]\\
    &\Rightarrow dA = \dfrac{1}{2}p^{-1/2}q^{1/2}r^{-2}s^{-3}dp + p^{1/2} \left\lbrace\left(\dfrac{1}{2}q^{-1/2}dq\right)r^{-2}s^{-3} + q^{1/2} \left[\left(-2r^{-3} dr\right) s^{-2} + r^{-2} \left(-3s^{-4}ds\right) \right]\right\rbrace\\
    &\Rightarrow dA = \dfrac{1}{2}p^{-1/2}q^{1/2}r^{-2}s^{-3} dp + \dfrac{1}{2}p^{1/2}q^{-1/2}r^{-2}s^{-3}dq - 2p^{1/2}q^{-2}r^{-3}s^{-3}dr - 3p^{1/2}q^{1/2}r^{-2}s^{-4}ds\\
    &\Rightarrow \dfrac{dA}{A} = \dfrac{1}{2} \dfrac{p^{-1/2}q^{1/2}r^{-2}s^{-3} dp}{p^{1/2}q^{1/2} r^{-2}s^{-3}} + \dfrac{1}{2} \dfrac{p^{1/2}q^{-1/2}r^{-2}s^{-3}dq}{p^{1/2}q^{1/2} r^{-2}s^{-3}} - 2 \dfrac{p^{1/2}q^{-2}r^{-3}s^{-3}dr}{p^{1/2}q^{1/2} r^{-2}s^{-3}} - 3 \dfrac{p^{1/2}q^{1/2}r^{-2}s^{-4}ds}{p^{1/2}q^{1/2} r^{-2}s^{-3}}\\
    &\Rightarrow \dfrac{dA}{A} = \dfrac{1}{2}\dfrac{dp}{p} + \dfrac{1}{2}\dfrac{dq}{q} - 2\dfrac{dr}{r} - 3 \dfrac{ds}{s}\\
    &\Rightarrow \dfrac{\Delta A}{A} = \dfrac{1}{2}\left(\pm \dfrac{\Delta p}{p}\right) + \dfrac{1}{2}\left(\pm \dfrac{\Delta q}{q}\right) - 2 \left(\pm \dfrac{\Delta r}{r}\right) - 3 \left(\pm \dfrac{\Delta s}{s}\right)\\
    & \Rightarrow \left(\dfrac{\Delta A}{A}\right)_{max} = max \left[\dfrac{1}{2}\left(\pm \dfrac{\Delta p}{p}\right) + \dfrac{1}{2}\left(\pm \dfrac{\Delta q}{q}\right) - 2 \left(\pm \dfrac{\Delta r}{r}\right) - 3 \left(\pm \dfrac{\Delta s}{s}\right)\right]\\
    &\Rightarrow \left(\dfrac{\Delta A}{A}\right)_{max} = \dfrac{1}{2}\dfrac{\Delta p}{p} + \dfrac{1}{2}\dfrac{\Delta q}{q} + 2 \dfrac{\Delta r}{r} + 3 \dfrac{\Delta s}{s}\\
    &\Rightarrow \left(\dfrac{\Delta A}{A}\right)_{max} = \dfrac{1}{2} \cdot 1\% + \dfrac{1}{2} \cdot 3\% + 2 \cdot 0,5\% + 3 \cdot 0,33\%\\
    &\Rightarrow \left(\dfrac{\Delta A}{A}\right)_{max} \approx 4\%
  \end{align*}
  \end{small}
  Resposta Correta: item C.
  \fimSol
  %%%%
  \item O comprimento de um pêndulo simples é de aproximadamente 100 cm, com uma precisão conhecida de 1 mm. Seu período de oscilação é de 2 s, determinado ao medir o tempo de 100 oscilações utilizando um relógio com resolução de 0,1 s. Qual é a precisão no valor determinado de $g$?
  \begin{enumerate}
    \item 0,2\%
    \item 0,1\%
    \item 0,5\%
    \item 2\%
  \end{enumerate}
  \iniSol
  O período de oscilação $T$ de um pêndulo simples de comprimento $L$ é dado por:
  $$
  T = 2\pi \sqrt{\dfrac{g}{L}}
  $$
  em que $g$ é a aceleração da gravidade.
  
  Isolando $g$, obtemos
  $$
  g = \dfrac{1}{4\pi^2}T^2 L
  $$
  Se $T$ foi medido como a média de $n = 100$ oscilações cuja duração total foi igual a $t$, temos:
  $$
  g = \dfrac{1}{4\pi^2} \left(\dfrac{t}{n}\right)^2L \Rightarrow  g = \dfrac{1}{4\pi n^2} t^2 L
  $$
  
  Tomanto a diferencial da expressão acima, obtemos:
  \begin{align*}
    dg = \dfrac{1}{4\pi n^2} \left(2t dt L + t^2 dL\right) &\Rightarrow \dfrac{dg}{g} = 2\dfrac{dt}{t} + \dfrac{dL}{L}\\
    &\Rightarrow \left(\dfrac{\Delta g}{g}\right)_{max} = 2\dfrac{\Delta t}{t} + \dfrac{\Delta L}{L}\\
    &\Rightarrow \left(\dfrac{\Delta g}{g}\right)_{max} = 2 \cdot \dfrac{0,1}{200} + \dfrac{1}{1000} = 0,002 = 0,2\%
  \end{align*}
  \fimSol
  %%%%
  \item A massa de uma bola é 1,76 kg, A massa destas bolas é:
  \begin{enumerate}
    \item $0,44\times 10^{3}$ kg
    \item $44,0$ kg
    \item $44$ kg
    \item $44,00$ kg
  \end{enumerate}
  \iniSol
    \begin{align*}
      M = 25 \times 1,76 = 44,0\text{kg}
    \end{align*}
    Resposta Correta: item B.
  \fimSol
  %%%%
  \item A menor divisão de um cronômetro é de 0,2 s. O tempo de 20 oscilações de um pêndulo foi medido como 25 s. O erro percentual no período é:
  \begin{enumerate}
    \item 1,2\%
    \item 0,8\%
    \item 1,8\%
    \item Nenhuma das anteriores.
  \end{enumerate}
  \iniSol
    Seja $T$ o período de oscilação, medido por meio  da média de $n$ oscilações com duração total igual a $t$. Assim, 
    \begin{align*}
      T = \dfrac{t}{n} &\Rightarrow dT = \dfrac{dt}{n} \Rightarrow \dfrac{dT}{T} = \dfrac{\dfrac{dt}{n}}{\dfrac{t}{n}} \Rightarrow \dfrac{dT}{T} = \dfrac{dt}{t}\\
      &\Rightarrow \dfrac{\Delta T}{T} = \dfrac{\Delta t}{t}\\
      &\Rightarrow \dfrac{\Delta T}{T} = = \dfrac{0,2}{25} 8 \times 10^{-3} = 0,8\%
    \end{align*}
    Resposta Correta: item B.
  \fimSol
  %%%%
\end{enumerate}



\newpage
\section*{Questões Subjetivas}

\begin{enumerate}
  \item Escreva o número de algarismos significativos das seguintes quantidades:
  \begin{enumerate}
    \item $6428$\\
    \iniSol
      $$
      6428 = 6,428 \times 10^{3} \Rightarrow 4 \text{ algarismos significativos}
      $$
    \fimSol
    \item $62,00$ m\\
    \iniSol
    $$
    62,00 \text{ m} = 6,200 \times 10^{3} \text{ m} \Rightarrow 4 \text{ algarismos significativos}
    $$
    \fimSol
    \item $0,00628$ cm\\
    \iniSol
    $$
    0,00628 \text{ cm} = 6,28 \times 10^{-3} \text{ cm} \Rightarrow 3 \text{ algarismos significativos}
    $$
    \fimSol
    \item $1200$ N \\
    \iniSol
    $$
    1200 \text{ N} = 1,2 \times 10^{2} \text{ N} \Rightarrow 2 \text{ algarismos significativos}
    $$
    \fimSol
  \end{enumerate}
  \item Escreva o número de dígitos significativos nas seguintes quantidades:
  \begin{enumerate}
    \item $1001$\\
    \iniSol
    $$
    1001 = 1,001 \times 10^{3} \Rightarrow 4 \text{ Dígitos Significativos}
    $$
    \fimSol
    \item $100,1$\\
    \iniSol
    $$
    100,1 = 1,001 \times 10^{2} \Rightarrow 4 \text{ Dígitos Significativos}
    $$
    \fimSol
    \item $100,10$\\
    \iniSol
    $$
    100,10 = 1,0010 \times 10^{2} \Rightarrow 5 \text{ Dígitos Significativos}
    $$
    \fimSol
    \item $0,001001$\\
    \iniSol
    $$
    0,001001 = 1,001 \times 10^{-3} \Rightarrow 4 \text{ Dígitos Significativos}
    $$
    \fimSol
  \end{enumerate}
  \item Indique o número de algarismos significativos nas seguintes quantidades:
  \begin{enumerate}
    \item $0,007\text{ m}^2$\\
    \iniSol
    $$0,007\;\text{m}^2 = 7 \times 10^{-3} \;\text{m}^2 \Rightarrow 1 \;\text{Algarismo Significativo}$$
    \fimSol
    \item $2,64 \times 10^{24}\text{ kg}$\\
    \iniSol
    $$2,64 \times 10^{24}\;\text{kg}  \Rightarrow 3 \;\text{Algarismos Significativos}$$
    \fimSol
    \item $0,2370\;\text{g/cm}^{3}$\\
    \iniSol
    $$0,2370\;\text{g/cm}^{3} = 2,370 \times 10^{-1}\;\text{g/cm}^{3}  \Rightarrow 4 \;\text{Algarismos Significativos}$$
    \fimSol
  \end{enumerate}
  \item Arredonde os seguintes números para 2 dígitos significativos:
  \begin{enumerate}
    \item $3472$\\
    \iniSol
    $$
      3472 = 3,472 \times 10^{3} \approx 3,5 \times 10^{3} = 3500
    $$
    \fimSol
    \item $84,16$\\
    \iniSol
    $$
    84,16 = 8,416 \times 10^{1} \approx 8,4 \times 10^{1} = 84
    $$
    \fimSol
    \item $2,55$\\
    \iniSol
    $$
      2,55 \approx 2,6 
    $$
    \fimSol
    \item $28,5$\\
    \iniSol
    $$
    28,5 = 2,85 \times 10^{1} \approx 2,8 \times 10^{1} = 28
    $$
    \fimSol
  \end{enumerate}
  \item Realize as seguintes operações:
  \begin{enumerate}
    \item $703 + 7 + 0,66$\\
    \iniSol
    $$
      R = 703 + 7 + 0,66 = 710,66
    $$
    Das três parcelas na operação de soma acima, o menor número de algarismos sigificativos após a vírgula é zero. Assim, o resultado deve ser arredondado para zero dígitos após a vírgula, ou seja, $R = 711$.
    \fimSol
    \item $2,21 \times 0,3$
    $$
      R = 2,21 \times 0,3 = 0,663
    $$
    O menor número de dígitos significativos nos fatores é igual a 1 (um). Assim, o resultado também deve ter apenas um dígito significativo, ou seja, $R = 0,7$.
    \item $12,4 \times 84$\\
    \iniSol
    $$
    R = 12,4 \times 84 = 1041,6 = 1,0416 \times 10^{3}
    $$
    O menor número de dígitos significativos nos fatores é igual a 2. Assim, o resultado também deve ter dois dígitos significativos, ou seja, 
    $$
    R = 1,0 \times 10^3 = 1000
    $$
    \fimSol
  \end{enumerate}
  \item Adicione $6,75 \times 10^3$ cm a $4,52 \times 10^2$ cm respeitanto a correta quantidade de algarismos significativos.\\
  \iniSol
  \begin{align*}
    R = 6,75 \times 10^3 + 4,52 \times 10^2 &= 6,75 \times 10^3 + 0,452 \times 10^3\\
    &= (6,75 + 0,452) \times 10^3 = 7,202 \times 10^{3}\\
    &= 7,20 \times 10^3 = 7200
  \end{align*}
  No resultado acima, a mantissa da notação científica deve apresentar uma quantidade de dígitos após a vírgula igual à parcela com menor quantidade de dígitos após a vírgula.
  \fimSol
  \item Calcule $\dfrac{25,2 \times 1374}{33,3}$. Todos os dígitos nesta expressão são significativos.\\
  \iniSol
  Dos termos na expressão dada, temos:
  \begin{table}[H]
    \centering
    \begin{tabular}{r c c}
      \hline
      Número & Qtd. Algarismos Significativos & Menor\\ \hline
      25,2 & 3 & *\\
      1374\; & 4 & \\
      33,3 & 3 & *\\
      \hline
    \end{tabular}
    A menor quantidade de algarismos significativos é 3. Assim, o resultado deve ser arredondado para três algarismos significativos:
  \end{table}
  \begin{align*}
    R = \dfrac{25,2 \times 1374}{33,3} = 1039,78378 = 1,03978378 \times 10^{3} = 1,040 \times 10^3
  \end{align*}
  \fimSol
  \item Resolva com a devida atenção aos algarismos significativos.
  $$
  (4,0 \times 10^{-4} - 2,5 \times 10^{-6})
  $$
  \iniSol
    Para realizar a operação de subtração (adição) com notação científica, o expoente da base deve ser o mesmo em todas as parcelas da operação, ou seja,
    \begin{align*}
    R = 4,0 \times 10^{-4} - 2,5 \times 10^{-6} &= 4,0 \times 10^{-4} - 0,025 \times 10^{-4}\\
    &= 3,975 \times 10^{-4}\\ 
    &= 4,0 \times 10^{-4}
    \end{align*}
    Note-se que o resultado foi arredondado para apresentar apenas um dógito após a vírgula pois esta é  menor quantidade de dígitos após a vírgula nas parcelas.
  \fimSol
  %%%%
  \item A massa de uma caixa medida por uma balança de mercearia é de 2,300 kg. Duas peças de ouro com massas de 20,15 g e 20,17 g são adicionadas à caixa. Qual é (a) a massa total da caixa, (b) a diferença entre as massas das peças, considerando os algarismos significativos corretos?\\
  \iniSol
    Considerando os algarismos significativos corretos, a massa do conjunto deve ser representada com a menor quantidade de dígitos após a vírgula, ou seja,
    $$
    M = 2,300 \;\text{kg} + 20,15 \;\text{g} + 20,17 \;\text{g} = 2,3 \;\text{kg} + 0,02015 \; \text{kg} + 0,02017 \; \text{kg} = 2,34032 \;\text{kg} = 2,3 \;\text{kg}
    $$
    
    A diferença entre as massas das peças de ouro é:
    $$
    \Delta m = 20,17 \; \text{g} - 20,15 \; \text{g} = 0,02 \; \text{g}
    $$
  \fimSol
  %%%%
  \item Um fio fino tem comprimento de 21,7 cm e raio de 0,46 mm. Calcule o volume do fio considerando os algarismos significativos corretos.\\
  \iniSol
  \begin{align*}
    V = \pi R^2 l &= \pi (0,46\;\text{mm})^2 \times (21,7\;\text{cm}) = \pi (0,046\;\text{cm})^2 \times (21,7\;\text{cm})\\
    &= 0,144253 \; \text{cm}^3\\
    &= 0,14 \; \text{cm}^3
  \end{align*}
  O resultado final foi apresentado com dois algarismos significativos pois esta é a menor quantidade de algarismos significativos nas parcelas da expressão para o volume.
  \fimSol
  %%%%
  \item Um cubo tem lado de comprimento $2,342$ m. Encontre o volume e a área superficial com a correta quantidade de algarismos significativos.\\
  \iniSol
    \begin{align*}
      &V = l^3 = (2,342\;\text{m})^3 = 12,85 \;\text{m}^3\\
      &S = l^2 = (2,342 \;\text{m})^2 = 5,485 \; \text{m}^2
    \end{align*}
  \fimSol
  %%%%
  \item Encontre a densidade quando uma massa de 9,23 kg ocupa um volume de 1,1 m$^3$. Considere os algarismos significativos.\\
  \iniSol
  \begin{align*}
    \rho = \dfrac{m}{V} &= \dfrac{9,23\;\text{kg}}{1,1\;\text{m}^3} = 8,4\;\text{kg/m}^3
  \end{align*}
  \fimSol
  %%%%
  \item O comprimento, a largura e a espessura de uma lâmina retangular são 4,234 m, 1,005 m e 2,01 m, respectivamente. Encontre o volume da lâmina considerando os algarismos significativos corretos.\\
  \iniSol
  \begin{align*}
    \begin{cases}
      l = 4,234\;\text{m}\\
      b = 1,005\;\text{m}\\
      t = 2,01\;\text{m}\\
    \end{cases}
    &\Rightarrow V = l \times b \times t \Rightarrow V = (4,234\;\text{m}) \times (1,005\;\text{m}) \times (2,01\;\text{m}) \\
    &\Rightarrow V = 8,55\;\text{m}^3
  \end{align*}
  \fimSol
  %%%%
  \item O raio de uma esfera é medido como $(2,1 \pm 0,5)$ cm. Calcule sua área de superfície com os limites de erro.\\
  \iniSol
    A área superficial $S$ de uma esfera de raio $R$ é
    $$
    S = 4\pi R^2 = 4 \pi (2,1)^2 = 55\;\text{cm}^2
    $$
    Tomando a diferencial total de $S$, temos:
    \begin{align*}
      dS = 4\pi (2RdR) &\Rightarrow \dfrac{dS}{S} = \dfrac{4\pi(2RdR)}{4\pi R^2} \Rightarrow \dfrac{dS}{S} = 2\dfrac{dR}{R}\\
      &\Rightarrow \dfrac{\Delta S}{S} = 2\dfrac{\Delta R}{R} \\
      & \Rightarrow \Delta S = 2 S \dfrac{\Delta R}{R}\\
      &\Rightarrow \Delta S = 2 (55) \dfrac{0,5}{2,1} = 26
    \end{align*}
    Portanto, considerando o limite de erro, temos
    $$
    S = (55 \pm 26) \;\text{cm}^2
    $$
  \fimSol
  %%%%
  \item A temperatura de dois corpos medida por um termômetro é $(20 \pm 0,5)$°C e $(50 \pm 0,5)$°C. Calcule a diferença de temperatura com os limites de erro.\\
  \iniSol
    \begin{align*}
      \Delta \theta = (50 - 20) + max\left[\pm 0,5 - (\pm 0,5)\right] = 30 \pm (0,5+0,5) = (30 \pm 1)^{\circ}\text{C}
    \end{align*}
  \fimSol
  %%%%
  \item A resistência $R = \dfrac{V}{I}$, onde $V = (100 \pm 5,0)$ V e $I = (10 \pm 0,2)$ A. Encontre o erro percentual em $R$\\
  \iniSol
    Tomando o diferencial total de $R = \dfrac{V}{I}$, temos,
    \begin{align*}
      dR = \dfrac{I dV - V dI}{I^2} &\Rightarrow \dfrac{dR}{R} = \dfrac{(I dV - V dI)}{I^2} \dfrac{I}{V} \Rightarrow \dfrac{dR}{R} = \dfrac{dV}{V} - \dfrac{dI}{I}\\
      &\Rightarrow \dfrac{\Delta R}{R} = \pm \dfrac{\Delta V}{V} - \left(\pm \dfrac{\Delta I}{I}\right) \Rightarrow \dfrac{\Delta R}{R} = \pm \dfrac{\Delta V}{V} \mp \dfrac{\Delta I}{I}\\
      &\Rightarrow \left(\dfrac{\Delta R}{R}\right)_{max} = max \left(\pm \dfrac{\Delta V}{V} \mp \dfrac{\Delta I}{I}\right)\\
      &\Rightarrow \left(\dfrac{\Delta R}{R}\right)_{max} = \dfrac{\Delta V}{V} + \dfrac{\Delta I}{I}\\
      &\Rightarrow \left(\dfrac{\Delta R}{R}\right)_{max} = \dfrac{5}{100} + \dfrac{0,2}{10} = 0,07 = 7\%
    \end{align*}
  \fimSol
\end{enumerate}




